### ISSUE TITLE
Binary package missing templates folder

### ISSUE THREAD

**Issue by Disonantemus** [chrishrb/go-grip#1]
### Downloading and testing [Last release](https://github.com/chrishrb/go-grip/releases/download/v0.2.0/go-grip-v0.2.0-linux-amd64.tar.gz), shows _error and exit:_
~~~ocaml
./go-grip
🚀 Starting server: http://localhost:80/README.md
2024/10/30 08:11:32 open templates/layout.html: no such file or directory
~~~

### Same happens when is installed using [README.md](https://github.com/chrishrb/go-grip#-getting-started):
~~~ocaml
go install github.com/chrishrb/go-grip@latest
~~~

### Workaround

Cloning the repo to get [templates folder](https://github.com/chrishrb/go-grip/tree/main/templates), fixed the problem, but **is cumbersome**, because _needs to be in same folder_ as markdown file to show. I think that folder **should** be included in the tarball or _better inside the binary_, or installed in `~/.config`.

---

### Machine:

~~~ocaml
distro: Arch Linux x86_64
kernel: 6.6.52-1-lts
shell: bash 5.2.37
term: tmux
~~~

**Comment by chrishrb** [comment]
Thanks for noticing it! Should be resolved now in #2.
