### ISSUE TITLE
Broken output

### ISSUE THREAD

**Issue by vbd** [chrishrb/go-grip#20]
At first thank you for your nice work. I was always looking for a simple local github renderer.

What I did (on Win11 Pro):

1. go install github.com/chrishrb/go-grip@latest
2. Download raw file version of README.md from https://github.com/chrishrb/go-grip/blob/main/README.md
3. go-grip -d .
4. select README.md

The output is a bit broken. I attached a screenshot and have numbered my comments.

1: missing image  
is due to how the graphic is included: <img src=".github/docs/logo-1.png" ...  
and the file is missing by only downloading README.md

2: mermaid diagram isn't showing  
console shows: Error: template: pattern matches no files: `templates\mermaid\mermaid.html`

3: Blockquotes are not renderd correct  
Probably similar topic to 2

4: border is ending/missing

5: paragraph start changed

6: missing example images  
Probably similar topic to 1

![159](https://github.com/user-attachments/assets/3fa34a11-8853-4858-bbcc-a0db84b5a16b)

**Comment by chrishrb** [comment]
so that the images and the mermaid block aren't rendered correct is no issue because the sources are not found. and it's intentional that these sources are imported relative and not absolute (e.g. over url)!
but you are right for the blockquotes: even if paths are incorrect, the blockquotes should be rendered correctly (and also the formatting of the whole html file should be ok). I will look into this!

**Comment by vbd** [comment]
I understand about the image files and had already assumed so.


Do you think it could make sense if you offer a zip-archive which includes all files to render the page fully local in sense of "To render the README.md file simply execute:"? 


To support for mermaid diagrams isn't it enough when a block like 

    ```mermaid
    graph TD;
          A-->B;
          A-->C;
          B-->D;
          C-->D;
    ```

is included? What does it need?

But for now I wish you a merry christmas - frohe Weihnachten and a good time!

**Comment by chrishrb** [comment]
So you had a good point here. It was indeed not working as expected on windows. I fixed most of your problems, the only one "missing" is the image problem, but for me this is not really a problem, so I won‘t change it.

Greetings and merry chrismas (i'm also german so, for me it's also: Frohe Weihnachten!)
