### ISSUE TITLE
Add option to remove bounding box

### ISSUE THREAD

**Issue by bynect** [chrishrb/go-grip#21]
This way exporting to html and printing will be easier.

**Comment by bynect** [comment]
thank you very much @chrishrb. Maybe it would be a good idea to deactivate the footer for printing.
I am trying to use go-grip with wkhtmltopdf to format a markdown page 😆

**Comment by chrishrb** [comment]
currently I try to add a native export feature to `go-grip`. Good idea to deactivate the footer here as well!
