### ISSUE TITLE
Support Mermaid diagrams

### ISSUE THREAD

**Issue by lidel** [chrishrb/go-grip#3]
Hi, the project is nearly perfect, only missing feature for my day-to-day needs is mermaid diagram support. Any change adding it?

Markdown Example: https://github.com/ipshipyard/p2p-forge/blob/12bb17edb06cef1f42b0e787662c1294c2704034/README.md

Ref.  https://github.blog/developer-skills/github/include-diagrams-markdown-files-mermaid/

Library: https://github.com/mermaid-js/mermaid

**Comment by chrishrb** [comment]
I implemented a basic version of it in #4. I have to run some tests and check if it looks and feels good - please give me also some feedback if this works (and looks) as expected!
