### ISSUE TITLE
Bad rendering: go-grip (grip) vs Github preview

### ISSUE THREAD

**Issue by Disonantemus** [chrishrb/go-grip#5]
As a reimplementation of [grip](https://github.com/joeyespo/grip) but local (without inet), is almost the same with my test files. But right now is not the same as GitHub markdown preview (GFM):

### Bad rendering examples (GFM vs grip/go-grip):

> GFM don't need two-spaces at the end of line for lineabreaks:

1st line.
2nd line.

> Numbered Start (Lists), should be: 57 & 58

57. foo
1. bar

> Smart Typography: in GFM should not be recognized

(c) (C)	copyright  
(r) (R)	registered  
(tm) (TM)	trademark  

> HTML Symbol Entities inside linecode

`&copy;` &copy;  
`&mdash;` &mdash;  
`&trade;` &trade;  

> HTML Symbol Entities  
[Character Entities for HTML, CSS and Javascript](https://oinam.github.io/entities/)

&euro; &yen; &pound; &dollar; &cent; &amp; &copy;  
&frac34; &plusmn; &sum; &int; &le; &asymp; &ang;  
&AElig; &Dcaron; &rArr; &darr; &lambda; &Gamma;

&Dagger; &mdash; &lang; &rang; &spades;  
&OElig; &aelig; &ouml;  
&weierp; &image; &real; &alefsym;  
&#35; &#1234; &#992; &#0; &#X22; 

&HilbertSpace; &ClockwiseContourIntegral; &DifferentialD;  
&#11165; &lceil; &rfloor; 
&nbsp;   
&#XD06; &#xcab;  

> Definition List: not supported in GFM but rendered ok in go-grip.

Apple
:   Pomaceous fruit of plants of the genus Malus in 
the family Rosaceae.

:   An American computer company.

Orange
:   The fruit of an evergreen tree of the genus Citrus.

First Term
: This is the definition of the first term.

Second Term
: This is one definition of the second term.
: This is another definition of the second term.

> Emojis

Camping :tent: Be back soon.
That is so funny! :joy:

Classic markup:  
:wink: :cry: :laughing: :yum: :tm:

> Math (Inline)

This is an inline $f(x)$ function.
This is a block $$f(x)$$ function.

> Math: KaTeX

$\sqrt{3x-1}+(1+x)^2$

> Math Block `\\[...\\]`

$${e}^{i\pi }+1=0$$

> Flow Charts (Mermaid)

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

> Headerless: GFM does not support this, but grip does!

|--|--|--|--|--|--|--|--|
|♜|  |♝|♛|♚|♝|♞|♜|
|  |♟|♟|♟|  |♟|♟|♟|
|♟|  |♞|  |  |  |  |  |
|  |♗|  |  |♟|  |  |  |
|  |  |  |  |♙|  |  |  |
|  |  |  |  |  |♘|  |  |
|♙|♙|♙|♙|  |♙|♙|♙|
|♖|♘|♗|♕|♔|  |  |♖|

**Comment by chrishrb** [comment]
Oh I didn't know about this spec. I will implement the missing parts as soon as possible! Thanks for this hint.

**Comment by chrishrb** [comment]
I created seperate issues for all of these issues. Some of them are already fixed (like mermaid or emojis)! 👍
